export const ProductActionTypes = {
    GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
    GET_ALL_CATEGORIES:'GET_ALL_CATEGORIES',
    GET_IN_CATEGORY:'GET_IN_CATEGORY',
    GET_SINGLE_PRODUCT: 'GET_SINGLE_PRODUCT',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    ADD_PRODUCT: 'ADD_PRODUCT',
    EDIT_PRODUCT: 'EDIT_PRODUCT',
}